alter table public.toilets
  add column if not exists place_kind text not null default 'community_toilet',
  add column if not exists has_toilet boolean not null default true,
  add column if not exists access_type text not null default 'public';

create table if not exists public.toilet_reports (
  id bigint generated by default as identity primary key,
  place_key text not null check (char_length(place_key) between 3 and 120),
  lat double precision not null check (lat between -90 and 90),
  lng double precision not null check (lng between -180 and 180),
  username text not null check (char_length(trim(username)) between 2 and 30),
  cleanliness integer not null check (cleanliness between 1 and 5),
  condition text not null check (condition in ('Хорошее', 'Среднее', 'Плохое')),
  has_paper boolean,
  has_soap boolean,
  wheelchair_accessible boolean,
  phone_charging boolean,
  access_type text not null default 'unknown'
    check (access_type in ('public', 'customers', 'permissive', 'destination', 'unknown')),
  comment text check (comment is null or char_length(comment) <= 300),
  created_at timestamptz not null default now()
);

create index if not exists toilet_reports_place_key_created_at_idx
  on public.toilet_reports (place_key, created_at desc);

alter table public.toilet_reports enable row level security;

drop policy if exists "Public reports are readable" on public.toilet_reports;
create policy "Public reports are readable"
  on public.toilet_reports for select
  to anon, authenticated
  using (true);

drop policy if exists "Public can add constrained reports" on public.toilet_reports;
create policy "Public can add constrained reports"
  on public.toilet_reports for insert
  to anon, authenticated
  with check (
    char_length(trim(username)) between 2 and 30
    and char_length(place_key) between 3 and 120
    and cleanliness between 1 and 5
    and condition in ('Хорошее', 'Среднее', 'Плохое')
    and (comment is null or char_length(comment) <= 300)
  );

grant select, insert on public.toilet_reports to anon, authenticated;
grant usage, select on sequence public.toilet_reports_id_seq to anon, authenticated;
