alter table public.toilet_reports
  add column if not exists has_toilet boolean;

create table if not exists public.place_submissions (
  id bigint generated by default as identity primary key,
  lat double precision not null check (lat between 40.45 and 55.55),
  lng double precision not null check (lng between 46.45 and 87.40),
  username text not null check (char_length(trim(username)) between 2 and 30),
  place_kind text not null
    check (place_kind in ('community_toilet', 'phone_charging', 'ev_charging')),
  is_free boolean not null,
  cleanliness integer not null check (cleanliness between 1 and 5),
  condition text not null check (condition in ('Хорошее', 'Среднее', 'Плохое')),
  comment text check (comment is null or char_length(comment) <= 300),
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected')),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  published_toilet_id bigint
);

create index if not exists place_submissions_status_created_at_idx
  on public.place_submissions (status, created_at desc);

alter table public.place_submissions enable row level security;
revoke all on public.place_submissions from anon, authenticated;
revoke all on sequence public.place_submissions_id_seq from anon, authenticated;

create or replace function public.submit_place(
  p_lat double precision,
  p_lng double precision,
  p_username text,
  p_place_kind text,
  p_is_free boolean,
  p_cleanliness integer,
  p_condition text,
  p_comment text default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  submission_id bigint;
begin
  if p_lat not between 40.45 and 55.55
     or p_lng not between 46.45 and 87.40 then
    raise exception 'Точка должна находиться в Казахстане';
  end if;

  insert into public.place_submissions (
    lat, lng, username, place_kind, is_free, cleanliness, condition, comment
  ) values (
    p_lat,
    p_lng,
    trim(p_username),
    p_place_kind,
    p_is_free,
    p_cleanliness,
    p_condition,
    nullif(trim(p_comment), '')
  )
  returning id into submission_id;

  return submission_id;
end;
$$;

revoke all on function public.submit_place(
  double precision, double precision, text, text, boolean, integer, text, text
) from public;
grant execute on function public.submit_place(
  double precision, double precision, text, text, boolean, integer, text, text
) to anon, authenticated;

create or replace function public.publish_approved_place_submission()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.status = 'approved' and old.status <> 'approved' then
    insert into public.toilets (
      lat,
      lng,
      username,
      is_free,
      cleanliness,
      condition,
      comment,
      place_kind,
      has_toilet,
      access_type
    ) values (
      new.lat,
      new.lng,
      new.username,
      new.is_free,
      new.cleanliness,
      new.condition,
      new.comment,
      new.place_kind,
      new.place_kind = 'community_toilet',
      'public'
    )
    returning id into new.published_toilet_id;
    new.reviewed_at = now();
  elsif new.status = 'rejected' and old.status <> 'rejected' then
    new.reviewed_at = now();
  end if;

  return new;
end;
$$;

drop trigger if exists publish_approved_place_submission
  on public.place_submissions;
create trigger publish_approved_place_submission
before update of status on public.place_submissions
for each row
execute function public.publish_approved_place_submission();
