create table if not exists public.place_votes (
  id bigint generated by default as identity primary key,
  place_key text not null check (char_length(place_key) between 3 and 120),
  voter_key text not null check (char_length(voter_key) between 12 and 80),
  is_current boolean not null,
  created_at timestamptz not null default now(),
  unique (place_key, voter_key)
);

alter table public.place_votes enable row level security;
revoke all on public.place_votes from anon, authenticated;

create or replace function public.cast_place_vote(
  p_place_key text,
  p_voter_key text,
  p_is_current boolean
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if char_length(p_place_key) not between 3 and 120 then
    raise exception 'Invalid place key';
  end if;

  if char_length(p_voter_key) not between 12 and 80 then
    raise exception 'Invalid voter key';
  end if;

  insert into public.place_votes (place_key, voter_key, is_current)
  values (p_place_key, p_voter_key, p_is_current)
  on conflict (place_key, voter_key)
  do update set
    is_current = excluded.is_current,
    created_at = now();
end;
$$;

create or replace function public.get_place_vote_totals()
returns table (place_key text, likes bigint, dislikes bigint)
language sql
stable
security definer
set search_path = public
as $$
  select
    place_votes.place_key,
    count(*) filter (where place_votes.is_current) as likes,
    count(*) filter (where not place_votes.is_current) as dislikes
  from public.place_votes
  group by place_votes.place_key;
$$;

revoke all on function public.cast_place_vote(text, text, boolean) from public;
revoke all on function public.get_place_vote_totals() from public;
grant execute on function public.cast_place_vote(text, text, boolean)
  to anon, authenticated;
grant execute on function public.get_place_vote_totals()
  to anon, authenticated;
